spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 543593943506-o4olj9gnsdjvupjn50fi7fhp0hr2iad9.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - image
          naver:
            client-id: o2NLqkJHmuhwRr9HCGq_
            client-secret: R8U1LbxPm4
            scope:
              - id
              - email
              - name
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response